feat: Update AWS ECR login process to handle token retrieval and improve error handling

diff --git a/templates/docker-build-to-aws.yml b/templates/docker-build-to-aws.yml
--- a/templates/docker-build-to-aws.yml
+++ b/templates/docker-build-to-aws.yml
@@ -9,42 +9,34 @@ parameters:
     type: string
   - name: repository
     type: string
+  - name: awsRegion
+    type: string
   - name: imageTag
     type: string
     default: '$(Build.BuildId)'
 
 steps:
   - bash: |
-      set -e
-      echo "--- Auto-découverte de la région AWS ---"
-      REGION=$(echo "${{ parameters.registryServer }}" | cut -d'.' -f4)
-      echo "Région détectée: $REGION"
-      echo "--- Authentification sur AWS ECR ---"
-      aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${{ parameters.registryServer }}
-    displayName: 'Smart Login to AWS ECR'
+      set -euo pipefail
+      echo "--- AWS ECR: génération du token + docker login ---"
+      ECR_TOKEN=$(aws ecr get-login-password --region "${{ parameters.awsRegion }}")
+
+      if [ -z "$ECR_TOKEN" ]; then
+        echo "##[error] Échec de la récupération du token AWS ECR."
+        exit 1
+      fi
+
+      echo "##vso[task.setvariable variable=SECURE_ECR_TOKEN;issecret=true]$ECR_TOKEN"
+    displayName: 'AWS ECR Login'
     env:
       AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
       AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
 
-  - bash: |
-      set -e
-      echo "--- Initialisation du moteur Docker Buildx ---"
-      docker buildx create --use --driver docker-container
-
-      echo "--- Lancement du Build avec Remote Caching ---"
-      docker buildx build \
-      --push \
-      --secret id=TOKEN,env=TOKEN \
-      --cache-from=type=registry,ref=${{ parameters.registryServer }}/${{ parameters.repository }}:buildcache \
-      --cache-to=type=registry,ref=${{ parameters.registryServer }}/${{ parameters.repository }}:buildcache,mode=max \
-      -t ${{ parameters.registryServer }}/${{ parameters.repository }}:${{ parameters.imageTag }} \
-      -f ${{ parameters.workingDir }}/Dockerfile \
-      ${{ parameters.workingDir }}
-    displayName: 'Build & Push with BuildKit Remote Cache'
-    env:
-      TOKEN: $(SECRET_TOKEN)
-
-  - bash: |
-      docker logout ${{ parameters.registryServer }}
-      displayName: 'Logout from AWS ECR'
-      condition: always()
+  - template: docker-build-and-push.yml
+    parameters:
+      workingDir: ${{ parameters.workingDir }}
+      registryServer: ${{ parameters.registryServer }}
+      registryUsername: 'AWS'
+      registryPassword: '$(SECURE_ECR_TOKEN)'
+      repository: ${{ parameters.repository }}
+      imageTag: ${{ parameters.imageTag }}
